- product: VPC Account
  description: "Basisaccount für Infrastrukturservices innerhalb der Virtual Private Cloud (VPC)"
  dependencies: []

- product: Avvia Cloud Foundation
  description: "Managed Service Produkt für VPC"
  dependencies:
    - type: required
      product: VPC Account

- product: Virtual Machine
  description: "Virtuelle Maschinen Service"
  alias: VM, VM Instance, Virtuelle Maschine, Server, Instance, Instanz
  dependencies:
    - type: required
      product: VPC Account
    - type: required
      product: Avvia Cloud Foundation
      
- product: Network Service
  description: "Netzwerkdienste innerhalb eines VPC Account"
  alias: Netzwerk Service, Netzwerkinfrastruktur, Netzwerk, Networking, Subnet, VLAN
  dependencies:
    - type: required
      product: VPC Account
    - type: required
      product: Avvia Cloud Foundation
	  
- product: Managed Kubernetes Cluster
  description: "Managed Kubernetes Clusters innerhalb eines VPC Account"
  alias: Kubernetes Cluster, K8s Cluster, K8s, Kubernetes, Container Plattform
  dependencies:
    - type: required
      product: VPC Account
    - type: required
      product: Avvia Cloud Foundation
	  
- product: Managed Kubernetes Worker
  description: "Kubernetes Worker in einem Managed Kubernetes Cluster"
  alias: Kubernetes Worker, K8s Worker, Node, K8s Node, Kubernetes Node
  dependencies:
    - type: required
      product: Managed Kubernetes Cluster
    - type: required
      product: Virtual Machine
 
- product: Loadbalancer
  description: "Loadbalancer Service"
  alias: LB, LBs, Load Balancer
  dependencies:
    - type: required
      product: VPC Account
    - type: required
      product: Avvia Cloud Foundation

- product: VPN-Tunnel
  description: "VPN Tunnel"
  alias: VPN Tunnel, VPN, S2S, Site-to-Site VPN
  dependencies:
    - type: required
      product: VPC Account
    - type: required
      product: Avvia Cloud Foundation